name: Build and Deploy .NET Project

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  NET-build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout Project Code'
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Build
      run: dotnet build Homeserver_GDrive/Homeserver_GDrive.csproj

  Docker-deploy:
    needs: NET-build
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout Project Code'
      uses: actions/checkout@v4
    - name: Set timestamp for tag
      run: echo "TIME_TAG=$(date +%Y%m%d_%H%M%S)" >> "$GITHUB_ENV"
    - name: 'Build and push image'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -f Homeserver_GDrive/Dockerfile --tag ${{ secrets.REGISTRY_LOGIN_SERVER }}/docker_homeserver_gdrive:homeserver_gdrive_$TIME_TAG --tag ${{ secrets.REGISTRY_LOGIN_SERVER }}/docker_homeserver_gdrive:latest
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/docker_homeserver_gdrive:homeserver_gdrive_$TIME_TAG

    
